# Site settings
title: Savage Adventures
email: info@savage-adventures.com
phone: "07895 834955"
customer_email: savageadventures@bookwild.app
description: >-
  Discover your primal side. Outdoor adventures including coasteering,
  canyoning, climbing, surfing and more across South Wales.
baseurl: ""
url: "https://savage-adventures.com"
twitter_username: sav_adventures

defaults:
  - scope:
      path: 'assets/images'
    values:
      image: true
  - scope:
      path: 'assets/images/header_images'
    values:
      header_image: true

# Build settings
plugins:
  - jekyll-feed
