backend:
  name: git-gateway
  branch: jekyll

site_url: https://vigilant-albattani-19faf8.netlify.app
local_backend: true

media_folder: 'assets/images/'
collections:
  - name: 'Config'
    label: 'Config'
    editor:
      preview: true
    files:
      - label: 'Home'
        name: 'home'
        file: 'index.html'
        fields:
          - { label: Layout, name: layout, widget: hidden, default: default }
          - { label: Title, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - { label: 'Body', name: 'body', widget: 'html' }

  - label: 'About Page'
    name: 'about'
    description: 'About us page'
    editor:
      preview: false
    files:
      - label: 'Page Intro'
        name: 'intro'
        file: '_includes/about/page-intro.md'
        fields:
        - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Team'
        name: 'team'
        file: '_data/team.yml'
        editor:
          preview: false
        fields:
          - label: 'Team Members'
            name: 'team_members'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Short Bio' ,name: 'bio' ,widget: 'text' }
              - label: 'Visible - do you want this to be visible on the site'
                name: 'visible'
                widget: 'boolean'
                default: false
      - label: 'Age Info'
        name: 'age-info'
        file: '_includes/age-info.md'
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Adventures Page'
    name: 'adventures'
    description: 'Top level adventures page with summaries'
    editor:
      preview: false
    files:
      - label: 'Page Intro'
        name: 'intro'
        file: 'adventures.html'
        fields:
          - { name: intro, label: 'Page Intro', widget: 'markdown' }
      - label: 'Adventures'
        name: 'adventures'
        file: '_data/adventures.yml'
        editor:
          preview: false
        fields:
          - label: 'Summaries'
            name: 'adventures'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Available - is this activity currently available'
                name: 'available'
                widget: 'boolean'
              - label: 'Visible - do you want this to be visible on the site'
                name: 'visible'
                widget: 'boolean'
                default: false
              - label: 'Stag & Hen - show this on the stag and hen page'
                name: 'stag-hen'
                widget: 'boolean'
                default: false

  - label: 'Corporate'
    name: 'corporate'
    description: 'Corporate page'
    editor:
      preview: false
    files:
      - label: 'Page Intro'
        name: 'intro'
        file: '_includes/corporate/page-intro.md'
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Stag-hen'
    name: 'stag-hen'
    description: 'Stag and Hen page'
    editor:
      preview: false
    files:
      - label: 'Page Intro'
        name: 'intro'
        file: '_includes/stag-hen/page-intro.md'
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }




