backend:
  name: git-gateway
  branch: jekyll
media_folder: "assets/images/uploads"
collections:
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "about" # Used in the UI
    folder: "_includes/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}