backend:
  name: git-gateway
  branch: jekyll

site_url: https://vigilant-albattani-19faf8.netlify.app
local_backend: true

media_folder: "assets/images/"
collections:
  - name: "Pages"
    label: "Pages"
    editor:
      preview: true
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: Layout, name: layout, widget: hidden, default: default }
          - { label: Title, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - { label: 'Body', name: 'body', widget: 'html' }

      - label: "Team"
        name: "team"
        file: "_data/team.yml"
        editor:
          preview: false
        fields:
          - label: 'Team Members'
            name: 'team_members'
            widget: 'list'
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Short Bio"
                name: "bio"
                widget: "text"
              - label: "Visible - do you want this to be visible on the site"
                name: "visible"
                widget: "boolean"
                default: false

      - label: "Adventures Top Page"
        name: "adventures"
        file: "_data/adventures.yml"
        editor:
          preview: false
        fields:
          - label: 'Adventure Summaries'
            name: 'adventures'
            widget: 'list'
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
              - label: "Description"
                name: "description"
                widget: "text"
              - label: "Available - is this activity currently available"
                name: "available"
                widget: "boolean"
              - label: "Visible - do you want this to be visible on the site"
                name: "visible"
                widget: "boolean"
                default: false




